---
apiVersion: apps/v1
kind: Deployment
metadata:
 name: dockerfiledeployment
spec:
 replicas: 2
 strategy: 
    type: Recreate
 selector: 
   matchLabels: 
     app: dockerfile
 template:
  metadata:
   name: Dockerfilepd
   labels:
     app: dockerfile	 
  spec: 
    containers:
    - name: dockerfilecontainer
      image: 
      imagePullPolicy: Always
      ports:
      - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
 name: mavenwebappsvc
spec:
  type: LoadBalancer
  selector:
   app: mavenwebapp
  ports:
   - port: 80
     targetPort: 8080
...
