---
apiVersion: apps/v1
kind: Deployment
metadata:
 name: dockerfiledeployment
spec:
 replicas: 2
 selector: 
   matchLabels: 
     app: dockerfile
 template:
  metadata:
   name: Dockerfilepod
   labels:
     app: dockerfile	 
  spec: 
    containers:
    - name: dockerfilecontainer
      image: gudapativaraprasad1987/dockerfile-gen
      imagePullPolicy: Always
      ports:
      - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
 name: dockerfilesvc
spec:
  type: LoadBalancer
  selector:
   app: dockerfile
  ports:
   - port: 80
     targetPort: 8080
...
